const productCategory = [
    { id : 1, label : "Aadhar Card Ke Liye", value : "Aadhar Card Ke Liye"},
    { id : 2, label : "Voter ID Card", value : "Voter ID Card"},
    { id : 3, label : "Rashan Card", value : "Rashan Card"},
    { id : 4, label : "Mahilaon Ki Yojana Ke Liye", value : "Mahilaon Ki Yojana Ke Liye"},
    { id : 5, label : "Pardhan Mantri Yojna Ke Liye", value : "Pardhan Mantri Yojna Ke Liye"},
    { id : 6, label : "Nali Ki Shikayat Ke Liye", value : "Nali Ki Shikayat Ke Liye"},
    { id : 7, label : "Sewer Ki Shikayat Ke Liye", value : "Sewer Ki Shikayat Ke Liye"},
    { id : 8, label : "Kude Ki Shikayat Ke Liye", value : "Kude Ki Shikayat Ke Liye"},
    { id : 9, label : "Bijli Bill Ki Shikayat Ke Liye", value : "Bijli Bill Ki Shikayat Ke Liye"},
    { id : 10, label : "MCD Ke Karmachaariyon Kee Shikaayat Ke Liye", value : "MCD Ke Karmachaariyon Kee Shikaayat Ke Liye"},
    { id : 11, label : "Gunda Kee Shikaayat Ke Liye", value : "Gunda Kee Shikaayat Ke Liye"},
    { id : 12, label : "Ladai Jhagada Kee Shikaayat Ke Liye", value : "Ladai Jhagada Kee Shikaayat Ke Liye"},
    { id : 13, label : "Gharelu Jhagada Kee Shikaayat Ke Liye", value : "watGharelu Jhagada Kee Shikaayat Ke Liyeches"},
    { id : 15, label : "Parking Kee Shikaayat Ke Liye", value : "Parking Kee Shikaayat Ke Liye"},
    { id : 16, label : "Pedon Kee Shikaayat Ke Liye", value : "Pedon Kee Shikaayat Ke Liye"},
    { id : 17, label : "Park Booking Ke Liye Shadi", value : "Park Booking Ke Liye Shadi"},
    { id : 18, label : "Mandir Booking Ke Liye Shadi", value : "Mandir Booking Ke Liye Shadi"},
    { id : 19, label : "Banquet Hall Booking Ke Liye Shadi", value : "Banquet Hall Booking Ke Liye Shadi"},
    { id : 20, label : "Mrtyu Ke Liye", value : "Mrtyu Ke Liye"},
    { id : 21, label : "Mandir Booking Ke Liye Mrtyu", value : "Mandir Booking Ke Liye Mrtyu"},
    { id : 22, label : "Banquet Hall Booking Ke Liye Mrtyu", value : "Banquet Hall Booking Ke Liye Mrtyu"},
    { id : 23, label : "Janamdin Ke Liye Invitation", value : "Janamdin Ke Liye Invitation"},
    { id : 24, label : "Banquet Hall Booking Ke Liye", value : "Banquet Hall Booking Ke Liye"},
    { id : 25, label : "Park Booking Ke Liye Janamdin", value : "Park Booking Ke Liye Janamdin"},
    { id : 26, label : "Mandir Booking Ke Liye Janamdin", value : "Mandir Booking Ke Liye Janamdin"},
    { id : 27, label : "Banquet Hall Booking Ke Liye Janamdin", value : "Banquet Hall Booking Ke Liye Janamdin"},
    { id : 28, label : "Hospital Udghatan Ke Liye", value : "Hospital Udghatan Ke Liye"},
    { id : 29, label : "School Udghatan Ke Liye", value : "School Udghatan Ke Liye"},
    { id : 30, label : "Collage Udghatan Ke Liye", value : "Collage Udghatan Ke Liye"},
    { id : 31, label : "Dukan Udghatan Ke Liye", value : "Dukan Udghatan Ke Liye"},
    { id : 32, label : "Sadak Udghatan Ke Liye", value : "Sadak Udghatan Ke Liye"},
    { id : 33, label : "Flyover Udghatan Ke Liye", value : "Flyover Udghatan Ke Liye"},
    { id : 34, label : "Ghar Udghatan Ke Liye", value : "Ghar Udghatan Ke Liye"},
    { id : 35, label : "Office Udghatan Ke Liye", value : "Office Udghatan Ke Liye"},
    { id : 36, label : "Shadi Ke Liye Card", value : "Shadi Ke Liye Card"},
    { id : 37, label : "Sagai Ke Liye Card", value : "Sagai Ke Liye Card"},
    { id : 38, label : "Party Meeting ke Liye", value : "Sagai Ke Liye Card"},
    { id : 39, label : "Other", value : "Other"},
]


export default productCategory